---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: MartinKuhl/ha-workflows/.github/workflows/addon-ci.yaml@0e05a3b9f0f50a1040d30feed6a68f0c5adc73a9 # main
