---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: MartinKuhl/ha-workflows/.github/workflows/pr-labels.yaml@0e05a3b9f0f50a1040d30feed6a68f0c5adc73a9 # main
